name: real_word
description: word

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.11.0
  url_launcher: ^6.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/real_word_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/data/org_data.json
    - assets/data/org_data_key_list.json
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
    - family: ComicNeue
      fonts:
        - asset: assets/fonts/ComicNeue-Light.ttf
          weight: 300
        - asset: assets/fonts/ComicNeue-Regular.ttf
          weight: 400
        - asset: assets/fonts/ComicNeue-Bold.ttf
          weight: 700

flutter_test:
  assets:
    - assets/
